apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: redis:latest
          ports:
            - containerPort: {{ .Values.port }}
              hostPort: {{ .Values.port }}
          env:
            - name: REDIS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: name
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: password
