apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  type: ClusterIP
